spring:
  jackson:
    serialization:
      indent_output: true

  h2:
    console:
      enabled: true
      path: /console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./testdb/testdb
    username: sa
    password:

mybatis:
  type-aliases-package: com.example.domain.repository,com.example.domain.model